In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from ...server.automl.neural_network.neural_network import NeuralNetwork
from ...server.automl.neural_network.fc_layer import FCLayer
from ...server.automl.neural_network.activation_layer import ActivationLayer
from ...server.automl.neural_network.activation_functions import tanh, tanh_derivative, relu, relu_derivative, sigmoid, sigmoid_derivative
from ...server.automl.neural_network.loss_functions import mse, mse_derivative, cross_entropy_binary, cross_entropy_binary_derivative, cross_entropy_multi_class, cross_entropy_multi_class_derivative
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from keras.utils import np_utils

In [2]:
#Lodaing data
X, Y = load_digits(return_X_y=True)
print(X.shape, Y.shape)
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2)
#Normalizing data
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
#Reshaping for the neural network
#X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
#X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1797, 64) (1797,)
(1437, 64) (360, 64) (1437, 10) (360, 10)


In [3]:
network = NeuralNetwork()
network.add(FCLayer(X_train.shape[1], 5))
network.add(ActivationLayer(relu, relu_derivative))
network.add(FCLayer(5, 2))
network.add(ActivationLayer(relu, relu_derivative))
network.add(FCLayer(2, 10))
network.add(ActivationLayer(sigmoid, sigmoid_derivative))
network.use(mse, mse_derivative)
network.fit(X_train, y_train, epochs=1000, learning_rate=0.1)
y_pred = np.array(network.predict(X_test))

c:\Users\Mohamed Ghallab\Desktop\GP\AutoML\notebooks\neural_network_generation\activation_functions.py:11: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [4]:
y_pred = y_pred.round()
print(y_test[0:3], y_test.shape)
print(y_pred[0:3], y_pred.shape)
print(accuracy_score(y_test, y_pred.round()))

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]] (360, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] (360, 10)
0.5638888888888889


In [7]:
clf = MLPClassifier(solver='lbfgs', alpha=0.1,
                                            hidden_layer_sizes=(5,2),
                                            max_iter=90000,activation='relu')
clf.fit(X_train, y_train)
y_pred_sk = clf.predict(X_test)
print(accuracy_score(y_test, y_pred_sk))

0.37222222222222223
