In [1]:
from ...server.automl.neural_network.neural_network import NeuralNetwork
from ...server.automl.neural_network.fc_layer import FCLayer
from ...server.automl.neural_network.activation_layer import ActivationLayer
from ...server.automl.neural_network.activation_functions import tanh, tanh_derivative
from ...server.automl.neural_network.loss_functions import mse, mse_derivative

from keras.datasets import mnist
from keras.utils import np_utils

In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(y_train.shape)
# training data : 60000 samples
# reshape and normalize input data
x_train = x_train.reshape(x_train.shape[0], 28*28)
x_train = x_train.astype('float32')
x_train /= 255
# encode output which is a number in range [0,9] into a vector of size 10
# number 3 will become [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
y_train = np_utils.to_categorical(y_train)
print(y_train.shape)
# same for test data : 10000 samples
x_test = x_test.reshape(x_test.shape[0], 28*28)
x_test = x_test.astype('float32')
x_test /= 255
y_test = np_utils.to_categorical(y_test)


(60000,)
(60000, 10)


In [3]:
# Network
net = NeuralNetwork()
net.add(FCLayer(28*28, 100))                # input_shape=(1, 28*28)    ;   output_shape=(1, 100)
net.add(ActivationLayer(tanh, tanh_derivative))
net.add(FCLayer(100, 50))                   # input_shape=(1, 100)      ;   output_shape=(1, 50)
net.add(ActivationLayer(tanh, tanh_derivative))
net.add(FCLayer(50, 10))                    # input_shape=(1, 50)       ;   output_shape=(1, 10)
net.add(ActivationLayer(tanh, tanh_derivative))

In [4]:
# train on 1000 samples
# as we didn't implemented mini-batch GD, training will be pretty slow if we update at each iteration on 60000 samples...
net.use(mse, mse_derivative)
print(x_test.shape)
print(y_test.shape) 
print(x_train.shape)
print(y_train.shape)
net.fit(x_train[0:1000], y_train[0:1000], epochs=35, learning_rate=0.1)

# test on 3 samples
out = net.predict(x_test[0:3])
print("\n")
print("predicted values : ")
print(out, end="\n")
print("true values : ")
print(y_test[0:3])

(10000, 784)
(10000, 10)
(60000, 784)
(60000, 10)


predicted values : 
[array([-0.00995142, -0.03860295, -0.22375582,  0.09110727,  0.00525162,
       -0.02444871,  0.0384272 ,  0.9177226 ,  0.13940064, -0.09772062]), array([ 0.91732712, -0.10318454,  0.69254214,  0.29485894, -0.01721983,
        0.3098501 ,  0.13637733, -0.81742777,  0.1079024 , -0.47567374]), array([-0.02353429,  0.99032109, -0.11732107, -0.00421549,  0.0166582 ,
        0.13786168,  0.11824858, -0.05052987,  0.04791648, -0.19975428])]
true values : 
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
