In [1]:
import numpy as np
import pandas as pd
from network_generator import NetworkGenerator
from neural_network import NeuralNetwork
from fc_layer import FCLayer
from activation_layer import ActivationLayer
from activation_functions import tanh, tanh_derivative, relu, relu_derivative, identity, identity_derivative
from loss_functions import mse, mse_derivative
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_squared_log_error
from sklearn.neural_network import MLPRegressor

In [2]:
data = pd.read_csv('../../../datasets/cleaned_datasets/cars_final.csv')
column = data["price"]
max_value = column.max()
min_value = column.min()
print(min_value, max_value) #5495.0 62990.0

5495.0 62990.0


In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    data.loc[:, data.columns != "price"], data["price"], test_size=0.20)
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)
X_test = np.asarray(X_test)
y_test = np.asarray(y_test)

In [4]:
clf = MLPRegressor(solver='lbfgs', alpha=0.01,
                                            hidden_layer_sizes=(5,2),
                                            max_iter=90000,activation='tanh')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(mean_squared_log_error(y_test, y_pred))

0.011602318797141874


In [4]:
network = NeuralNetwork()
#hidden_layer_sizes = [X_train.shape[1], 38, 36, 32, 22, 16, 1]
hidden_layer_sizes = [X_train.shape[1], 36,32, 1]
for i in range(len(hidden_layer_sizes) - 1):
    network.add(FCLayer(hidden_layer_sizes[i], hidden_layer_sizes[i + 1]))
    if i < len(hidden_layer_sizes) - 2:
        network.add(ActivationLayer(tanh, tanh_derivative))
network.add(ActivationLayer(identity, identity_derivative))
network.use(mse, mse_derivative)
network.fit(X_train, y_train, epochs=2000, learning_rate=0.1, batch_size=16)
y_pred = np.nan_to_num(network.predict(X_test))
print(y_test, y_test.shape)
print(y_pred, y_pred.shape)
print(mean_squared_log_error(y_test, y_pred))
#y_test_true_value = y_test * (62990.0 - 5495.0) + 5495.0
#y_pred_true_value = y_pred * (62990.0 - 5495.0) + 5495.0
#print(mean_squared_log_error(y_test_true_value, y_pred_true_value))
# print(y_pred_true_value)

epoch 1/2000   error=23932717284275859901370154108313102325733090169225555656911286159617222556029835754873403300252901097399350176889240158140887175235835933125606159240176599040.000000
epoch 2/2000   error=0.000000
epoch 3/2000   error=0.000000
epoch 4/2000   error=0.000000
epoch 5/2000   error=0.000000
epoch 6/2000   error=0.000000
[14495.  6299. 28400. ... 25995. 12995. 21950.] (1447,)
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]] (1447, 1)
97.75236478948582


In [33]:
network = NeuralNetwork()
network.add(FCLayer(X_train.shape[1], 5))
network.add(ActivationLayer(tanh, tanh_derivative))
network.add(FCLayer(5, 2))
network.add(ActivationLayer(tanh, tanh_derivative))
network.add(FCLayer(2, 1))
network.add(ActivationLayer(identity, identity_derivative))
network.use(mse, mse_derivative)
network.fit(X_train, y_train, epochs=2000, learning_rate=0.001, batch_size=32)
y_pred = np.array(network.predict(X_test))
print(y_test, y_test.shape)
print(y_pred, y_pred.shape)
print(mean_squared_log_error(y_test, y_pred))

[0.2781981  0.08652926 0.27019741 ... 0.18076354 0.24367336 0.33924689] (1447,)
[[0.27317881]
 [0.27317881]
 [0.27317881]
 ...
 [0.27317881]
 [0.27317881]
 [0.27317881]] (1447, 1)
0.011088663958199853
