In [1]:
import numpy as np
import pandas as pd
from network_generator import NetworkGenerator
from neural_network import NeuralNetwork
from fc_layer import FCLayer
from activation_layer import ActivationLayer
from activation_functions import tanh, tanh_derivative, relu, relu_derivative, identity, identity_derivative
from loss_functions import mse, mse_derivative
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_squared_log_error
from sklearn.neural_network import MLPRegressor

In [2]:
data = pd.read_csv('../../../datasets/cleaned_datasets/cars_final.csv')

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    data.loc[:, data.columns != "price"], data["price"], test_size=0.20)
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)
X_test = np.asarray(X_test)
y_test = np.asarray(y_test)

In [4]:
clf = MLPRegressor(solver='sgd', alpha=0.1,
                                            hidden_layer_sizes=(5,2),
                                            max_iter=90000,activation='tanh', random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(mean_squared_log_error(y_test, y_pred)) # clf.loss_curve_ ,clf.best_loss_, 

0.1554998866427396


In [5]:

network = NeuralNetwork()
hidden_layer_sizes = [X_train.shape[1], 38, 36, 32, 22, 16, 1]
#hidden_layer_sizes = [X_train.shape[1], 5,2, 1]
for i in range(len(hidden_layer_sizes) - 1):
    network.add(FCLayer(hidden_layer_sizes[i], hidden_layer_sizes[i + 1]))
    if i < len(hidden_layer_sizes) - 2:
        network.add(ActivationLayer(tanh, tanh_derivative))
network.add(ActivationLayer(identity, identity_derivative))
network.use(mse, mse_derivative)
network.fit(X_train, y_train, epochs=2000, learning_rate=0.01, batch_size=16)
y_pred = np.array(network.predict(X_test))
print(y_test, y_test.shape)
print(y_pred, y_pred.shape)
print(mean_squared_log_error(y_test, y_pred))

epoch 1/2000   error=68861093.524462
epoch 2/2000   error=295425209.379401
epoch 3/2000   error=88859150.078399
epoch 4/2000   error=51761315.660298
epoch 5/2000   error=41684872.927505
epoch 6/2000   error=40684725.344521
epoch 7/2000   error=40552061.641834
epoch 8/2000   error=40550683.444592
epoch 9/2000   error=40740708.814005
epoch 10/2000   error=40219798.777785
epoch 11/2000   error=40335303.520933
epoch 12/2000   error=40346413.626481
epoch 13/2000   error=40077095.456696
epoch 14/2000   error=39964442.362951
epoch 15/2000   error=40096445.287945
epoch 16/2000   error=40286401.065997
epoch 17/2000   error=40058414.027090
epoch 18/2000   error=40061095.614303
[19888. 22599. 29000. ... 12490. 17498. 20000.] (1447,)
[[23777.80919947]
 [23777.80919947]
 [23777.80919947]
 ...
 [13811.47747262]
 [23777.80919947]
 [23777.80919947]] (1447, 1)
0.07999429592839183


In [5]:
network = NeuralNetwork()
network.add(FCLayer(X_train.shape[1], 5))
network.add(ActivationLayer(tanh, tanh_derivative))
network.add(FCLayer(5, 2))
network.add(ActivationLayer(tanh, tanh_derivative))
network.add(FCLayer(2, 1))
network.add(ActivationLayer(identity, identity_derivative))
network.use(mse, mse_derivative)
network.fit(X_train, y_train, epochs=2000, learning_rate=0.1, batch_size=8)
y_pred = np.array(network.predict(X_test))
print(y_test, y_test.shape)
print(y_pred, y_pred.shape)
print(mean_squared_log_error(y_test, y_pred))

[14995. 19930. 10799. ... 23000. 33500. 15399.] (1447,)
[[21217.17178641]
 [21217.17178641]
 [21217.17178641]
 ...
 [21217.17178641]
 [21217.17178641]
 [21217.17178641]] (1447, 1)
0.15513629650086247
